name: SonarQube Scan


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v1
      with:
        args: >
          -Dsonar.projectKey=ditto-analisi
          -Dsonar.host.url=http://localhost:9000
          -Dsonar.login=$SONAR_TOKEN
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: http://localhost:9000
